name: buildfork

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: ubuntu-latest
   needs: build
   environment:
     name: production
     url: http://flat-wound.surge.sh
   steps:
     - name: download build artifacts
       uses: actions/download-artifact@v5.0.0
       with:
         name: build
     - name: deploy
       run: npx surge --project '.' --domain http://flat-wound.surge.sh
       env:
         SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
         SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: cache
        uses: actions/cache@v4.3.0
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage
        uses: actions/upload-artifact@v4.6.2
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: build
      
